<?php
/** 3 perces részletes bemutató – fejezetekre bontva, felirat + zene. */

$chapter = function (string $num, string $title, string $sub = '') {
    return ['type' => 'hero', 'theme' => 'wheat', 'kicker' => $num,
        'text' => $title, 'sub' => $sub, 'small' => true, 'dur' => 2.0, 'motion' => 'in'];
};

return [
    /* =========================================================== 0. HOOK */
    ['type' => 'hero', 'text' => 'Ki vette meg|tavaly a ~rozsot~?', 'dur' => 1.8, 'motion' => 'in'],
    ['type' => 'hero', 'text' => 'Mennyi az|~AKG-s~ területe?', 'dur' => 1.6, 'motion' => 'out'],
    ['type' => 'hero', 'text' => 'Miért nem vett|tőlünk ~idén~?', 'dur' => 1.6, 'motion' => 'in'],
    ['type' => 'hero', 'small' => true,
        'text' => 'Ez a tudás ma a fejekben|és a füzetekben van.', 'dur' => 2.4, 'motion' => 'out'],
    ['type' => 'hero', 'theme' => 'wheat', 'kicker' => 'Vetőmag CRM', 'small' => true,
        'text' => 'Egy rendszer, ami|~agrár-értékesítésre~ épült.',
        'sub' => 'Nem általános CRM, amit mezőgazdaságra kell hajlítani.', 'dur' => 3.0, 'motion' => 'in'],
    ['type' => 'card', 'img' => '01-vezerlopult', 'badge' => 'Vezérlőpult',
        'text' => 'Reggel ez az első képernyő', 'dur' => 2.6, 'motion' => 'in'],
    ['type' => 'split', 'img' => '01-vezerlopult', 'badge' => 'Vezérlőpult',
        'text' => 'A számok,|amikre figyelsz',
        'list' => ['Árbevétel havi bontásban', 'Ajánlat → üzlet konverzió', 'Hívások és látogatások', 'Megyei megoszlás'],
        'dur' => 3.4, 'motion' => 'out'],

    /* ==================================================== 1. PARTNEREK */
    $chapter('01 · Partnerek', 'Minden, amit egy|gazdálkodóról tudni kell'),
    ['type' => 'screen', 'img' => '02-partnerlista', 'badge' => 'Partnerlista', 'corner' => true,
        'text' => 'Egy törzs, nem hat Excel',
        'sub' => 'Kereshető, szűrhető megyére, szegmensre, státuszra.', 'dur' => 3.0, 'motion' => 'in'],
    ['type' => 'split', 'img' => '03-partner-adatlap', 'badge' => 'Partner adatlap',
        'text' => 'Agrár-mezők,|nem „megjegyzés"',
        'list' => ['Terület, AKG-részvétel és -terület', 'Kultúrák, állatállomány, öntözés', 'Tervezett és korábbi zöldítés', 'Vásárlási motivációk, versenytárs-ajánlatok'],
        'dur' => 4.2, 'motion' => 'out'],
    ['type' => 'screen', 'img' => '37-nevjegyzek', 'badge' => 'Névjegyzék', 'corner' => true,
        'text' => 'Google-névjegyek|kétirányú szinkronnal', 'dur' => 2.4, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '24-piaci-szereplok', 'badge' => 'Piaci szereplők', 'corner' => true,
        'text' => 'Akik még nem vevők –|de lehetnének',
        'sub' => 'Több ezer soros Excel is importálható, egy kattintás a partnerré minősítés.',
        'dur' => 3.0, 'motion' => 'left'],
    ['type' => 'screen', 'img' => '25-prospect-terkep', 'corner' => true,
        'text' => 'És ők is|ott vannak a térképen', 'dur' => 2.4, 'motion' => 'in'],

    /* ==================================================== 2. ÁRAJÁNLAT */
    $chapter('02 · Árajánlat', 'Az igénytől a kiküldött|PDF-ig egy folyamat'),
    ['type' => 'screen', 'img' => '06-arajanlat-szerk', 'badge' => 'Árajánlat', 'corner' => true,
        'text' => 'Élő előnézet:|pontosan ezt kapja az ügyfél',
        'sub' => 'Kedvezmény, szállítási díj, ÁFA – magától számolódik.', 'dur' => 3.6, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '05-arajanlat-uj', 'corner' => true,
        'text' => 'Koppints a keverékre –|már benne is van',
        'sub' => 'Összetétel, kiszerelés, vetési norma, utóvetemény minden csempén.',
        'dur' => 3.2, 'motion' => 'out'],
    ['type' => 'split', 'img' => '10-kalkulator', 'badge' => 'Keverék-kalkulátor',
        'text' => 'Hány zsák kell|40 hektárra?',
        'sub' => 'Terület és keverék alapján mennyiség, zsákszám, ár. Nem fejben számolsz a partner asztalánál.',
        'dur' => 3.4, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '07-arajanlatok', 'corner' => true,
        'text' => 'Kiküldve · elfogadva|· elvesztve – és miért',
        'sub' => 'Minden kiküldött ajánlathoz automatikus utánkövetési emlékeztető.',
        'dur' => 3.2, 'motion' => 'left'],
    ['type' => 'screen', 'img' => '08-eladasok', 'badge' => 'Értékesítés', 'corner' => true,
        'text' => 'Az elfogadott ajánlatból|egy kattintás az eladás', 'dur' => 2.8, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '09-arlista', 'badge' => 'Árlisták', 'corner' => true,
        'text' => 'Kereskedői, végfelhasználói|és viszonteladói ár', 'dur' => 2.6, 'motion' => 'out'],

    /* ======================================================== 3. TEREP */
    $chapter('03 · Terep', 'Ami az irodán kívül|történik'),
    ['type' => 'screen', 'img' => '04-terkep', 'badge' => 'Térkép', 'corner' => true,
        'text' => 'Minden partner|a térképen',
        'sub' => 'Látod, hol van fehér folt a megyében.', 'dur' => 3.0, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '16-napi-tura', 'badge' => 'Napi túra', 'corner' => true,
        'text' => 'A napi kör|útvonalba rendezve',
        'sub' => 'Kijelölöd a partnereket, a rendszer sorba teszi őket. Táv és idő azonnal látszik.',
        'dur' => 3.6, 'motion' => 'out'],
    ['type' => 'screen', 'img' => '26-csapadek', 'badge' => 'Csapadéktérkép', 'corner' => true,
        'text' => 'Hol esett az éjjel|és mennyi?', 'dur' => 2.6, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '28-muholdas', 'badge' => 'Műhold', 'corner' => true,
        'text' => 'Vegetációs állapot|a partner tábláin', 'dur' => 2.6, 'motion' => 'left'],
    ['type' => 'screen', 'img' => '27-mepar', 'badge' => 'MePAR', 'corner' => true,
        'text' => 'Blokkazonosítók|és területek', 'dur' => 2.4, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '43-latogatasok', 'badge' => 'Látogatások', 'corner' => true,
        'text' => 'Hol jártál,|mi lett belőle', 'dur' => 2.4, 'motion' => 'out'],
    ['type' => 'screen', 'img' => '17-turak', 'badge' => 'Túrák', 'corner' => true,
        'text' => 'A megtett körök|visszakereshetők', 'dur' => 2.3, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '29-zoldtragya', 'badge' => 'Zöldtrágya', 'corner' => true,
        'text' => 'Keveréktábla összetétellel|és vetési normával', 'dur' => 2.6, 'motion' => 'left'],

    /* =============================================== 4. KAPCSOLATTARTÁS */
    $chapter('04 · Kapcsolattartás', 'A telefon a legfontosabb|értékesítési eszköz'),
    ['type' => 'phone', 'img' => 'm1-bejovo-hivas', 'badge' => 'Bejövő hívás',
        'text' => 'Csörög a telefon –|és már látod, ki az.',
        'sub' => 'Név, cég, előzmény, tavalyi vásárlás – még felvétel előtt a képernyőn.',
        'dur' => 4.0, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '12-hivasnaplo', 'badge' => 'Hívásnapló', 'corner' => true,
        'text' => 'A telefonnapló|magától frissül',
        'sub' => 'A szám alapján a hívás a partnerhez kerül, jegyzettel együtt.', 'dur' => 3.2, 'motion' => 'out'],
    ['type' => 'screen', 'img' => '13-hivasterv', 'badge' => 'Híváslista', 'corner' => true,
        'text' => 'Kit hívj ma?',
        'sub' => 'Szűrők alapján összeállított napi hívólista, nyomtatható is.', 'dur' => 2.8, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '11-hivaslista', 'corner' => true,
        'text' => 'A napi hívások|egy listában', 'dur' => 2.3, 'motion' => 'out'],
    ['type' => 'screen', 'img' => '14-teendok', 'badge' => 'Teendők', 'corner' => true,
        'text' => 'Kanban-tábla|a CRM-be építve', 'dur' => 2.6, 'motion' => 'left'],
    ['type' => 'screen', 'img' => '15-naptar', 'badge' => 'Naptár', 'corner' => true,
        'text' => 'Látogatások, túrák,|határidők egy helyen', 'dur' => 2.6, 'motion' => 'in'],

    /* ============================================= 5. PIAC ÉS KIMUTATÁS */
    $chapter('05 · Piac és számok', 'Mi történik körülötted|és mi lett a munkádból'),
    ['type' => 'screen', 'img' => '22-piacfigyelo', 'badge' => 'Piacfigyelő', 'corner' => true,
        'text' => 'Versenytárs-termékek|és árak egy helyen', 'dur' => 2.8, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '23-ar-osszehasonlito', 'corner' => true,
        'text' => 'Mennyivel vagy olcsóbb|vagy drágább?', 'dur' => 2.6, 'motion' => 'out'],
    ['type' => 'screen', 'img' => '18-kimutatas', 'badge' => 'Kimutatások', 'corner' => true,
        'text' => 'Mi fogy, hol, kinek',
        'sub' => 'Termék, megye, partner és időszak szerint – exportálható.', 'dur' => 3.2, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '20-korabbi-eladasok', 'corner' => true,
        'text' => 'A tavalyi rendelés|egy keresés',
        'sub' => 'A korábbi évek adatai importálva, azonnal kereshetők.', 'dur' => 3.0, 'motion' => 'left'],
    ['type' => 'screen', 'img' => '40-tamogatasi-lista', 'badge' => 'Támogatási lista', 'corner' => true,
        'text' => 'Kinek van AKG-s|kötelezettsége?',
        'sub' => 'Célzott megkeresés hideghívás helyett.', 'dur' => 3.0, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '21-piaci-jelenlet', 'badge' => 'Piaci jelenlét', 'corner' => true,
        'text' => 'Hol vagy erős|és hol nem', 'dur' => 2.6, 'motion' => 'out'],
    ['type' => 'screen', 'img' => '19-heti-jelentes', 'corner' => true,
        'text' => 'Heti jelentés,|exportálva a vezetőnek', 'dur' => 2.4, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '38-tervek', 'badge' => 'Tervek', 'corner' => true,
        'text' => 'Célok és teljesülésük', 'dur' => 2.2, 'motion' => 'left'],
    ['type' => 'screen', 'img' => '39-koltsegeim', 'badge' => 'Költségeim', 'corner' => true,
        'text' => 'Üzemanyag, szállás,|autópálya – blokkal', 'dur' => 2.4, 'motion' => 'out'],

    /* ==================================================== 6. ÜGYNÖKÖK */
    $chapter('06 · Ügynökök', 'AI-segéderő –|a te felügyeleteddel'),
    ['type' => 'screen', 'img' => '36-asszisztens', 'badge' => 'Asszisztens', 'corner' => true,
        'text' => 'Kérdezz rá|a saját adataidra',
        'sub' => 'Csak a CRM belső adatából dolgozik. Kérésre teljesen helyben futó modellel is.',
        'dur' => 3.6, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '34-adatdusito', 'badge' => 'Adatdúsító', 'corner' => true,
        'text' => 'Hiányos partneradatok|kiegészítése', 'dur' => 2.6, 'motion' => 'out'],
    ['type' => 'screen', 'img' => '32-samu-prof', 'badge' => 'Szaktanácsadó', 'corner' => true,
        'text' => 'Szakmai válaszok|a saját dokumentumaidból', 'dur' => 2.8, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '31-karmester', 'badge' => 'Karmester', 'corner' => true,
        'text' => 'Az ügynököket|egy kéz fogja össze', 'dur' => 2.6, 'motion' => 'left'],
    ['type' => 'screen', 'img' => '35-email-kampanyok', 'badge' => 'E-mail ügynök', 'corner' => true,
        'text' => 'Kampánylevelek|több fiókból', 'dur' => 2.4, 'motion' => 'out'],
    ['type' => 'screen', 'img' => '30-kalaszos', 'badge' => 'Szaktanácsadás', 'corner' => true,
        'text' => 'Fajtaadatok|forrásmegjelöléssel',
        'sub' => 'A hiányzó adatok a NÉBIH Nemzeti Fajtajegyzékéből tölthetők.', 'dur' => 3.0, 'motion' => 'in'],

    /* ======================================================= 7. ZÁRÁS */
    ['type' => 'phone', 'img' => 'm3-vezerlopult-mobil', 'img2' => 'm4-arajanlat-mobil', 'badge' => 'Mobil',
        'text' => 'Zsebben is|a teljes rendszer.',
        'sub' => 'Telepíthető alkalmazásként, app-store nélkül. A képernyők mobilra készültek, nem kicsinyített asztali nézetek.',
        'dur' => 4.0, 'motion' => 'in'],
    ['type' => 'stat', 'theme' => 'light', 'dur' => 2.6, 'motion' => 'in', 'items' => [
        ['9', 'modul'], ['40+', 'képernyő'], ['2', 'perc egy ajánlat'],
    ]],
    ['type' => 'hero', 'small' => true,
        'text' => 'Nem prototípus.|~Élesben megy~, minden nap,|egy magyar vetőmagcégnél.', 'dur' => 3.2, 'motion' => 'out'],
    ['type' => 'outro', 'text' => 'Nézd meg élőben, a saját adataitokkal.|Írj, és megbeszéljük.',
        'url' => 'balazsfoldhazi.github.io/vetomag-crm-bemutato', 'dur' => 4.0, 'motion' => 'in'],
];
