<?php
/** 60 másodperces teaser – pörgős vágás, felirat + zene, narráció nélkül. */

return [
    /* ------------------------------------------------------------- HOOK */
    ['type' => 'hero', 'text' => 'Ki vette meg|tavaly a ~rozsot~?', 'dur' => 1.7, 'motion' => 'in'],
    ['type' => 'hero', 'text' => 'Mennyi az|~AKG-s~ területe?', 'dur' => 1.5, 'motion' => 'out'],
    ['type' => 'hero', 'text' => 'Mikor beszéltetek|~utoljára~?', 'dur' => 1.5, 'motion' => 'in'],
    ['type' => 'hero', 'small' => true, 'text' => 'Ha ez csak a fejekben van,|~egy felmondással elmegy.~', 'dur' => 2.4, 'motion' => 'out'],
    ['type' => 'hero', 'theme' => 'wheat', 'kicker' => 'Vetőmag CRM',
        'text' => 'Egy rendszer, ami|~agrár-értékesítésre~ épült.', 'small' => true, 'dur' => 2.3, 'motion' => 'in'],

    /* ---------------------------------------------------------- MONTÁZS */
    ['type' => 'screen', 'img' => '02-partnerlista', 'badge' => 'Partnerek', 'corner' => true,
        'text' => 'Minden partner|egy törzsben', 'dur' => 1.7, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '03-partner-adatlap', 'corner' => true,
        'text' => 'Hektár, AKG, kultúrák,|korábbi vásárlások', 'dur' => 1.8, 'motion' => 'left'],
    ['type' => 'screen', 'img' => '06-arajanlat-szerk', 'badge' => 'Árajánlat', 'corner' => true,
        'text' => 'Ajánlat percek alatt', 'dur' => 1.7, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '05-arajanlat-uj', 'corner' => true,
        'text' => 'Koppints a keverékre', 'dur' => 1.4, 'motion' => 'out'],
    ['type' => 'screen', 'img' => '10-kalkulator', 'corner' => true,
        'text' => 'Hány zsák kell|40 hektárra?', 'dur' => 1.6, 'motion' => 'out'],
    ['type' => 'screen', 'img' => '07-arajanlatok', 'corner' => true,
        'text' => 'Kiküldve · elfogadva|· utánkövetve', 'dur' => 1.5, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '08-eladasok', 'corner' => true,
        'text' => 'Az ajánlatból|egy kattintás az eladás', 'dur' => 1.5, 'motion' => 'left'],
    ['type' => 'screen', 'img' => '04-terkep', 'badge' => 'Terep', 'corner' => true,
        'text' => 'A partnereid|a térképen', 'dur' => 1.7, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '16-napi-tura', 'corner' => true,
        'text' => 'A napi kör|útvonalba rendezve', 'dur' => 1.8, 'motion' => 'out'],
    ['type' => 'screen', 'img' => '26-csapadek', 'corner' => true,
        'text' => 'Hol esett az éjjel?', 'dur' => 1.4, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '28-muholdas', 'corner' => true,
        'text' => 'Műholdas|vegetációs térkép', 'dur' => 1.4, 'motion' => 'left'],
    ['type' => 'screen', 'img' => '27-mepar', 'corner' => true,
        'text' => 'MePAR-blokkok', 'dur' => 1.2, 'motion' => 'in'],
    ['type' => 'phone', 'img' => 'm1-bejovo-hivas', 'badge' => 'Hívás', 'corner' => true,
        'text' => 'Csörög a telefon –|és már látod, ki az.',
        'sub' => 'Név, előzmény, tavalyi vásárlás. Felvétel előtt.', 'dur' => 2.2, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '12-hivasnaplo', 'corner' => true,
        'text' => 'Minden hívás|a partnerhez kötve', 'dur' => 1.5, 'motion' => 'out'],
    ['type' => 'screen', 'img' => '14-teendok', 'corner' => true,
        'text' => 'Teendők, határidők', 'dur' => 1.3, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '13-hivasterv', 'corner' => true,
        'text' => 'Kit hívj ma?', 'dur' => 1.3, 'motion' => 'left'],
    ['type' => 'screen', 'img' => '18-kimutatas', 'badge' => 'Kimutatás', 'corner' => true,
        'text' => 'Mi fogy, hol, kinek', 'dur' => 1.6, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '20-korabbi-eladasok', 'corner' => true,
        'text' => 'A tavalyi rendelés|egy keresés', 'dur' => 1.5, 'motion' => 'out'],
    ['type' => 'screen', 'img' => '22-piacfigyelo', 'badge' => 'Piac', 'corner' => true,
        'text' => 'Versenytárs-árak|egy helyen', 'dur' => 1.6, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '40-tamogatasi-lista', 'badge' => 'Támogatások', 'corner' => true,
        'text' => 'Kinek van AKG-s|kötelezettsége?', 'dur' => 1.6, 'motion' => 'left'],
    ['type' => 'screen', 'img' => '45-tamogatas-hektar', 'corner' => true,
        'text' => 'A támogatásból|kijön a hektár', 'dur' => 1.7, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '30-kalaszos', 'badge' => 'Szaktanácsadás', 'corner' => true,
        'text' => 'Fajtaadatok|kéznél', 'dur' => 1.4, 'motion' => 'in'],
    ['type' => 'screen', 'img' => '31-karmester', 'badge' => 'Ügynökök', 'corner' => true,
        'text' => 'AI-ügynökök –|a te felügyeleteddel', 'dur' => 1.7, 'motion' => 'out'],
    ['type' => 'screen', 'img' => '36-asszisztens', 'corner' => true,
        'text' => 'Kérdezz rá|a saját adataidra', 'dur' => 1.6, 'motion' => 'in'],
    ['type' => 'phone', 'img' => 'm3-vezerlopult-mobil', 'img2' => 'm4-arajanlat-mobil',
        'badge' => 'Mobil', 'corner' => true,
        'text' => 'Zsebben is|a teljes rendszer.',
        'sub' => 'Telepíthető alkalmazásként. App-store nélkül.', 'dur' => 2.2, 'motion' => 'left'],

    /* ------------------------------------------------------------ ZÁRÁS */
    ['type' => 'stat', 'theme' => 'light', 'dur' => 2.0, 'motion' => 'in', 'items' => [
        ['40+', 'képernyő'], ['9', 'modul'], ['0', 'Excel-fájl'],
    ]],
    ['type' => 'hero', 'text' => 'Nem prototípus.|~Élesben megy~, minden nap.', 'small' => true, 'dur' => 2.4, 'motion' => 'out'],
    ['type' => 'outro', 'text' => 'Agrár-értékesítés egy rendszerben.|Nézd meg a részletes bemutatót:',
        'url' => 'balazsfoldhazi.github.io/vetomag-crm-bemutato', 'dur' => 3.4, 'motion' => 'in'],
];
